DATA_DIRECTORY = "./data"

TRADING_DATA_FILE_DIRECTORY = f"{DATA_DIRECTORY}/trading.csv"

TEST_DATA_FILE_DIRECTORY = f"{DATA_DIRECTORY}/statistics"

PROCESSED_DATA_FILENAME = "trading-data"

START_YEAR_FOR_DATA = 2015
